### ISSUE TITLE
Feedback for the exploration of the dataset (Bids_Exploration.ipynb)

### ISSUE THREAD

**Issue by JNPauli** [JNPauli/Mental-image-decoding#6]
Hi! 
Im creating this issue, because I wanted to get some feedback on the current state of the exploration notebook. I included everything that had been discussed in the last meeting, and want to know what further Information can be provided in the notebook.

Best

Janos

**Comment by PeerHerholz** [comment]
Hi,

I think the overall structure is good but the content could be enriched with more details and a narrative structure IMHO.
While there are some explanations in certain parts, others don't have any explanation or very little. Togethr with the absent overall narrative it might get hard for folks to follow what's happening and what information/data is present.

- the notebook might be more suitable in the `data` directory
- a short overview at the beginning would be great
- maybe providing more background information on the study the dataset comes from and incorporating the respective parts of this notebook would be nice (e.g. in the original study participants performed the following tasks ..... . Here we are going to explore an example for task ... . )
- adding an overview graphic for the task(s), ie an example for the task structure/content

 As I already spent some time with the dataset as well I think feedback from less biased folks would be great, for example @maren7794 and maybe someone else.

**Comment by marenwehrheim** [comment]
Hi, 
I agree with Peer that the file still needs a bit more of "why" and "what". So why do you explore a certain file? Why do you put the code there? What does it contain and what does it tell you? At the moment you only show what you can do but not what it means. For example, right in the beginning when you print all files, why would it be interesting to know the number of files? There seem to be no meaningful entries in that files list, why print this?
I also strongly support the last two bullet points from Peer. For me, it was still not clear what the tasks and the exact structure of your dataset were. I would suggest a few figures on:

1.  The general task that participants performed. When was perception, when imagery? How long? How often? How many? What images? etc.
2. What is the exact structure of the dataset? Something like the folder structure on the BIDS website would be very helpful. 

You could also divide part 2 into the exploration of the brain data (2A) and the task (2B). From your heading of 2, I would expect you to only examine the brain data but you also look into the general task structure. That's a bit confusing. 

Additionally, think of changing the y label of your category id vs. onset(s) plot to small numbers or meaningful strings. What about the resting states in between? Add a title -> was this imagery or perception? This feedback is supposed to be very general for figure-making. A figure should be understandable on its own.

Also, did you include a reference to the paper where the data set was published?

**Comment by JNPauli** [comment]
@PeerHerholz @maren7794 I tried to incooperate most of your comments. I hope the paradigm and task structure is more clear now!

However Im not 100% sure how I should include "What is the exact structure of the dataset? Something like the folder structure on the BIDS website would be very helpful." 

Is the structure not clear already, because this is a BIDS validated Dataset?
